# Default Window Size
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Title
SCREEN_TITLE = "The Epic of Goat by Team Pastafobia"
FULLSCREEN = False
FULLSCREEN_WINDOWED = False

# Config
CENTER_WINDOW = False
CURSOR_VISIBLE = False

# Refresh Rate
TARGET_REFRESH_RATE = 60
TARGET_REFRESH_TIME = 1 / TARGET_REFRESH_RATE
