from const.window import *

GLOBAL_SCALE = SCREEN_WIDTH / 1280
CHARACTER_SCALING = 1 * GLOBAL_SCALE
BULLET_SCALING = 1 * GLOBAL_SCALE
ENEMY_SCALING = 0.8*GLOBAL_SCALE
BG_SCALING = 1.0 * GLOBAL_SCALE
GOLD_SCALING = 0.5 * GLOBAL_SCALE
WEAPON_SCALING = 0.1 * GLOBAL_SCALE
