# This workflow will install Python dependencies, test and upload a code coverage report with Python 3.8, 3.9 and 3.10
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code Coverage

on:
  push:
    paths: "**.py"
  pull_request:
    paths: "**.py"
  workflow_dispatch:

jobs:
  code_coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "requirements.txt"
      - name: Run Tests
        run: |
          pip install nose2
          python -m nose2
      - name: Generate XML Report
        run: |
          pip install coverage
          coverage xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
          fail_ci_if_error: true
