name: Windows Build

on:
  push:
    paths: "**.py"
  pull_request:
    paths: "**.py"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "requirements-dev.txt"
      - name: Create package with PyInstaller
        run: |
          pyinstaller The_Epic_of_Goat.spec
